const Data = [
{
  id:'1',
  title:'Kaziranga National Park',
  category:'North-East',
  state:'Assam',
  img:"https://images.unsplash.com/photo-1655288212750-dedac22f84d7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Kaziranga National Park, a UNESCO World Heritage Site since 1985, harbors two-thirds of the world's great one-horned rhinoceros population and boasts the highest density of tigers globally. Declared a tiger reserve in 2006, it's also a habitat for wild water buffaloes, Swamp Deers, and elephants. Its diverse ecosystem and rare wildlife make it a conservation priority.",
},
{
  id:'2',
  title:'Tawang Monaestry',
  category:'North-East',
  state:'Arunachal-Pradesh',
  img:"https://images.unsplash.com/photo-1628070018796-a9f4e2dd482a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Tawang Monastery, nestled in Tawang city, Arunachal Pradesh, is India's largest and the world's second-largest monastery. Perched at 10,000 feet in the Tawang River valley, it offers a celestial retreat. Its serene ambiance and stunning views make it a spiritual haven, drawing visitors seeking peace and enlightenment amidst the Himalayan landscape.",
},
{
  id:'3',
  title:'Nathu La Pass',
  category:'North-East',
  state:'Sikkim',
  img:"https://images.unsplash.com/photo-1697561832430-daebcb737292?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Nathu La Pass, situated 54km east of Gangtok in Sikkim, connects India with China's Tibet Autonomous Region. At 4,310 meters above sea level, it's a historic part of the Silk Route. Closed after the 1962 Sino-Indian War, it reopened in 2006 for limited trade, offering breathtaking views and a glimpse into history.",
},
{
  id:'4',
  title:'Darjeeling',
  category:'East',
  state:'West-Bengal',
  img:"https://images.unsplash.com/photo-1622308644420-b20142dc993c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Darjeeling, a picturesque hill station in East India, captivates with its stunning scenery, mesmerizing sunrises, and old-world charm. Nestled amidst lush green tea plantations at 2,050 meters above sea level, it offers a romantic escape. About 700 kilometers from Kolkata, Darjeeling's cool climate and welcoming locals make it an ideal honeymoon destination.",
},
{
  id:'5',
  title:'Konark',
  category:'East',
  state:'Odisha',
  img:"https://images.unsplash.com/photo-1576235282476-debff2a4d0b9?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Konark, Odisha, famed for its UNESCO-listed Sun Temple, hosts an annual dance festival attracting talent nationwide. Against the temple's backdrop, the five-day event showcases cultural richness. Konark's sandy beaches also host the Sun Festival, where devotees bathe to honor the Sun God. The festivities include a Handicrafts Mela, spotlighting Odisha's intricate artistry, enriching the vibrant cultural tapestry.",
},
{
  id:'6',
  title:'Rann of Kutch',
  category:'West',
  state:'Gujarat',
  img:"https://images.unsplash.com/photo-1669015881702-951de590db31?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"The Great Rann of Kutch, a vast salt marshland in Gujarat's Kutch district, mesmerizes with its Thar Desert charm. Sunsets here are breathtaking. Divided into the Great and Little Ranns, it's renowned for salt deposits that create stunning mirages. Featured in Indian films like 'Refugee' and books like Salman Rushdie's 'Midnight's Children,' it's celebrated for its natural splendor and cultural significance.",
},
{
  id:'7',
  title:'Calangute Beach',
  category:'West',
  state:'Goa',
  img:"https://images.unsplash.com/photo-1589428000126-afdd64ae1f3a?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Calangute Beach, North Goa's longest stretch from Candolim to Baga, draws global tourists for its vibrant atmosphere. Known as the 'Queen of Beaches,'' it ranks among the world's top ten bathing spots. Bustling with eateries and water sports like parasailing and jet-skiing, it offers day and night excitement. Its strategic location facilitates easy access to nearby beaches, making it a preferred stay option in Goa.",
},
{
  id:'8',
  title:'Agra',
  category:'North',
  state:'Uttarpradesh',
  img:"https://images.unsplash.com/photo-1519955266818-0231b63402bc?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Agra, renowned globally for the Taj Mahal and Mughal-era monuments, stands as a cultural hub on the Yamuna's banks. Its architectural marvels include tombs, palaces, and forts, reflecting the grandeur of the Mughal Empire. From Akbar's tomb to Shah Jahan's gardens, Agra entices with its rich heritage, making it a top destination in Uttar Pradesh for cultural exploration.",
},
{
  id:'9',
  title:'Shalimar Bagh',
  category:'North',
  state:'Jammu & Kashmir',
  img:"https://images.pexels.com/photos/16930780/pexels-photo-16930780/free-photo-of-shalimar-bagh-mughal-garden-in-srinagar-india.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  des:"Srinagar boasts three Mughal-era gardens, with Shalimar Bagh being the largest and most renowned. Combining natural beauty with exquisite architecture, it captivates nature and history enthusiasts alike. Adorned with greenery, waterfalls, and Chinar trees, it's considered Srinagar's crown jewel. Located 10 km from the city center, it's easily accessible by public transport, inviting travelers to immerse themselves in its splendor.",
},
{
  id:'10',
  title:'Bijapur',
  category:'South',
  state:'Karnataka',
  img:"https://images.pexels.com/photos/18320285/pexels-photo-18320285/free-photo-of-gol-gumbaz-mausoleum-in-bijapur.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  des:"Bijapur, Karnataka, is a treasure trove of historical wonders dating back to the 10th century. Its architectural marvels, including Gol Gumbaz and Jamiya Masjid, showcase Mughal heritage. Easily accessible by road and rail, Bijapur offers visitors a glimpse into its rich past. From Fort Bijapur to Shivgiri Shiva Temple, the city brims with attractions, ensuring an enriching experience for history enthusiasts and travelers alike. Accessible via NH50 from Hampi, Bijapur promises a memorable journey through time.",
},
{
  id:'11',
  title:'Ooty',
  category:'South',
  state:'Tamilnadu',
  img:"https://images.unsplash.com/photo-1589136777351-fdc9c9cab193?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  des:"Ooty, Tamil Nadu, captivates with its verdant hills and vibrant flower gardens, often gracing Bollywood screens. Its tea estates and terraced farming evoke awe, while colonial-era architecture adds a historical charm. The lush landscape, dotted with waterfalls, offers respite from urban life. Attractions like botanical gardens and Doddabetta Peak beckon travelers to explore this picturesque hill station. Accessible from Mysore via scenic routes, Ooty promises a delightful journey through nature's bounty.",
},
];

export default Data
